### ISSUE TITLE
While moving camera (headtracking) weird stop while using wheelup

### ISSUE THREAD

**Issue by Forsaken-Player** [skiselkov/StopZoomingDammit#1]
Hello!!! 
great idea! great pluggin!
As said in the title if I use the mouse wheel up while moving the camera to screen stutters, but if I do the same with wheel down it doesn't occur.

**Comment by skiselkov** [comment]
This is expected behavior and "not really a bug". It's just a quirk of the implementation. When we detect X-Plane is attempting to zoom without the button being pressed down, we "reset" the view to its last position without zoom. Because this position is by definition 1 frame old, there's going to be a little bit of view judder going on. Sadly, there's no way to change this without completely reimplementing how the plugin works.
